GET http://localhost:5020/games

###
GET http://localhost:5020/games/2

###
POST http://localhost:5020/games
Content-Type: application/json

{
    "name": "Fantastic 4",
    "genreId": 1,
    "price": 59.99,
    "releaseDate": "2023-06-01"
}

###
PUT http://localhost:5020/games/2
Content-Type: application/json

{
    "name": "Dest 5V",
    "genre": "Horror",
    "price": 10.98,
    "releaseDate": "2001-04-12"
}

###
DELETE http://localhost:5020/games/1

###
GET http://localhost:5020/genres