GET http://localhost:5020/games

###
GET http://localhost:5020/games/8

###
POST http://localhost:5020/games
Content-Type: application/json

{
    "name": "",
    "genre": "Action",
    "price": 99.90,
    "releaseDate": "2023-06-23"
}

###
PUT http://localhost:5020/games/2
Content-Type: application/json

{
    "name": "Final Destination IV",
    "genre": "Horror",
    "price": 10.98,
    "releaseDate": "2001-04-12"
}

###
DELETE http://localhost:5020/games/1